[project]
requires-python = ">= 3.9"

[tool.poetry]
name = "list-sync"
version = "0.3.1"
description = ""
authors = ["Woahai321"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"
bs4 = "^0.0.2"
halo = "^0.0.31"
colorama = "^0.4.6"
cryptography = "^43.0.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.0"
